<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="MAIN_oo" Id="{dd06f3b9-f114-454f-820d-85f29a3eb792}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_oo
VAR
	
	// network interface/simulator function blocks
	netiMeshCal				:FB_3eTI_iMesh_Cal;
	netiMeshTESIM			:FB_3eTI_iMesh_TESIM;
	netiMeshTestSignals		:FB_3eTI_TestSignals;
	netiMeshLFSR			:FB_3eTI_iMesh_LFSR;
	
	netPCCal				:FB_PC_OneLink_Cal;
	netPCTESIM				:FB_PC_OneLink_TESIM;
	netPCTestSignals		:FB_PC_OneLink_TestSignals;
	netPC_LFSR				:FB_PC_LFSR;

	netNoNet				:FB_NoNet;
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

CASE NET_TYPE OF 
	100:
	netiMeshCal();
	101:
	netiMeshTESIM();
	102:
	netiMeshTestSignals();
	110:
	netiMeshLFSR();
	
	200:
	netPCCal();
	201:
	netPCTESIM();
	202:
	netPCTestSignals();
	210:
	netPC_LFSR();
	
ELSE
	netnoNet();
	
END_CASE]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>